### ISSUE TITLE
Add loading bars/spinning balls when waiting for an action to happen.

### ISSUE THREAD

**Issue by lauraferrarese** [lluttrell/NGVS-map-tool#20]
On my browser (Firefox 76.0.1), there is no way for the use to know whether anything is happening if an action takes too long (I know it works on yours!).

**Comment by lluttrell** [comment]
Loaders should hopefully work everywhere now

**Comment by lauraferrarese** [comment]
They work for me!!!! And I really like the little pop up that tells you how many objects were loaded when you "apply" a catalogue!
